// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Department struct {
	DeptNo          string       `json:"dept_no"`
	DeptName        string       `json:"dept_name"`
	ValidFrom       time.Time    `json:"valid_from"`
	ValidTo         time.Time    `json:"valid_to"`
	TransactionTime sql.NullTime `json:"transaction_time"`
}

type DeptEmp struct {
	EmpNo           int64        `json:"emp_no"`
	DeptNo          string       `json:"dept_no"`
	ValidFrom       time.Time    `json:"valid_from"`
	ValidTo         time.Time    `json:"valid_to"`
	TransactionTime sql.NullTime `json:"transaction_time"`
}

type DeptManager struct {
	EmpNo           int64        `json:"emp_no"`
	DeptNo          string       `json:"dept_no"`
	ValidFrom       time.Time    `json:"valid_from"`
	ValidTo         time.Time    `json:"valid_to"`
	TransactionTime sql.NullTime `json:"transaction_time"`
}

type Employee struct {
	EmpNo           int64        `json:"emp_no"`
	BirthDate       time.Time    `json:"birth_date"`
	FirstName       string       `json:"first_name"`
	LastName        string       `json:"last_name"`
	Gender          string       `json:"gender"`
	HireDate        time.Time    `json:"hire_date"`
	ValidFrom       time.Time    `json:"valid_from"`
	ValidTo         time.Time    `json:"valid_to"`
	TransactionTime sql.NullTime `json:"transaction_time"`
}

type Salary struct {
	EmpNo           int64        `json:"emp_no"`
	Salary          int64        `json:"salary"`
	ValidFrom       time.Time    `json:"valid_from"`
	ValidTo         time.Time    `json:"valid_to"`
	TransactionTime sql.NullTime `json:"transaction_time"`
}

type Title struct {
	EmpNo           int64        `json:"emp_no"`
	Title           string       `json:"title"`
	ValidFrom       time.Time    `json:"valid_from"`
	ValidTo         time.Time    `json:"valid_to"`
	TransactionTime sql.NullTime `json:"transaction_time"`
}
